### ISSUE TITLE
Only allows 1 note to be saved 

### ISSUE THREAD

**Issue by hoenn321** [CosmicVarion/tada#65]
Page can only save 1 note at a time upon signing out it deletes everything after the first created note.

**Comment by simranlall** [comment]
I'm not able to recreate the bug. Can you please try again and if the problem persists, send the list of steps you took that made this happen?

**Comment by hoenn321** [comment]
I found out that it's not actually  a bug. The user has to click the E to make it S in order to save the pinned note. Sorry for the confusion.

**Comment by hoenn321** [comment]
It was not said explicitly so as a user with no experience and with no readme I did not find the s and e function to mean anything.
