### ISSUE TITLE
Added a 2nd event but the calendar does not go to the newly created event

### ISSUE THREAD

**Issue by hoenn321** [CosmicVarion/tada#67]
Added a 2nd event but the calendar still stays on the first event created. So cannot find the newly created event unless manually going left/right

**Comment by simranlall** [comment]
Can be more specific about this bug? I'm unsure of what you mean by 'stays on the first event created'

**Comment by hoenn321** [comment]
I guess it wouldn't be a bug but a future add-on. Sorry for the confusion.

**Comment by hoenn321** [comment]
The calendar does not go to the newly created event at all. I.E Am on Oct. 10 2017. And created an event on Jan. 10 2018. The calendar does not move to Jan. 10 2018 when event is created. Plus since there is no tab we have to go to Jan 2018 manually. Problem is the calendar is meant to keep track of items so let's say I had an event on Jan 1 2018. And i totally don't remember. And when it's Dec 31 2017 the calendar won't show  that there's an event the next day (since it's in the next month and if I don't remember it's there then I'm in trouble!).
