### ISSUE TITLE
Bug: page is rendered incorrectly after login

### ISSUE THREAD

**Issue by ghost** [CosmicVarion/tada#80]
If I log out and log back in, there's a "?" at the end of the route, and only the bottom half of the page is rendered, making it unusable. However, if I hit the back button, the "?" goes away, and the page looks normal again.

**Comment by simranlall** [comment]
It renders fine when I login. Is this bug common for you?

**Comment by ghost** [comment]
I just tried to reproduce the bug, and I cannot. The page now renders fine with or without a `?` at the end of the route.

**Comment by cosmicvarion** [comment]
Resolved with separation of landing and app page.
